const AСTypes = {
    AUTH: "AUTH",
    CHECK_AUTH: "CHECK_AUTH",
    PROFILE: "PROFILE",
    UPDATE_CONNECTIONS: "UPDATE_CONNECTIONS",
    CONNECTIONS: "CONNECTIONS",
    GET_INVESTORS: "GET_INVESTORS",
  };

export default AСTypes
